version: '3'
services:
  api:
    image: <dockerhub name>/<name of image> #pull image instead of building it for production
    depends_on:
      - postgres
    ports:
      - "80:8000" # port is 80 because we run it on the web

    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

    # env_file:
    #   - ./1api.env
    
    # We use Env variables on the hosting machine instead:
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}

  postgres:
    image: postgres
    # env_file:
    #   - ./1db.env
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: